macro( compiler_req )
    if( CMAKE_CXX_COMPILER_ID STREQUAL "GNU" )
      if( CMAKE_CXX_COMPILER_VERSION VERSION_LESS "5.0" )
        message( FATAL_ERROR "Insufficient g++ version, at least 5.0 is required" )
      endif()
    elseif( CMAKE_CXX_COMPILER_ID STREQUAL "Clang" )
      if( CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.0" )
        message( FATAL_ERROR "Insufficient Clang version, at least 4.0 is required" )
      endif()
    endif()
endmacro( compiler_req )
