macro( use_cxx11 )
    include( CheckCXXCompilerFlag )
    CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
    CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)

    if( COMPILER_SUPPORTS_CXX11 )
        if( CMAKE_VERSION VERSION_LESS "3.1" )
            if( CMAKE_CXX_COMPILER_ID STREQUAL "GNU" )
                set( CMAKE_CXX_FLAGS "--std=gnu++11 ${CMAKE_CXX_FLAGS}" )
            else()
                set( CMAKE_CXX_FLAGS "--std=c++11 ${CMAKE_CXX_FLAGS}" )
            endif()
        else()
            set( CMAKE_CXX_STANDARD 11 )
        endif()
    elseif( COMPILER_SUPPORTS_CXX0X )
        set( CMAKE_CXX_FLAGS "--std=c++0x ${CMAKE_CXX_FLAGS}" )
    else()
        message( FATAL_ERROR "= Compiler ${CMAKE_CXX_COMPILER} has no C++11 support =" )
    endif()
endmacro( use_cxx11 )
